rm(list = ls()); library(xtable)
## This script will generate the strategy performance statistics for
## analyzing all the strategies.
##
## The statistics are generated by customized functions which have
## been designed keeping in mind the specifications of the strategy
## backtest result data sets.
##
## The analysis functions are imported from the
## './analyze_strategy_functions.R' script.
##
## The strategy performance dataframe created by this script is
## converted to the latex format by xatble package. This table is then
## manually pasted into '../doc/report_strategy_performance.tex'
## script to generate the final pdf report of the strategies.

                                        # load strategy performance functions
source('./analyze_strategy_functions.R')

                                        # record various srategy backtest results
files <- list.files(path = '../strategy_results/', full.names = TRUE)
strategy_names <- list.files(path = '../strategy_results/', full.names = FALSE)
strategy_names <- gsub(pattern = '.RData', replacement = '', x = strategy_names)
strategy_names <- gsub(pattern = '-', replacement = ' ', x = strategy_names)
strategy_names <- gsub(pattern = '_', replacement = ' ', x = strategy_names)

                                        # duration of simulation (in days)
load('../data/main_data.RData')
m_data <- data; rm(data)
sim_range <- as.numeric(m_data$date[nrow(m_data)] - m_data$date[1])

                                        # get S&P 500 time series
data_snp <- m_data$snp; names(data_snp) <- m_data$date
rm(m_data); gc()

                                        # get strategy performance statistics
strat_results <- lapply(X = files,
                        FUN = function(k)
                        {
                          load(k); ip <- result
                          ip$buy_date <- as.POSIXct(ip$buy_date)
                          ip$sell_date <- as.POSIXct(ip$sell_date)
                          op <- c(get_total_ret(data = ip), get_avg_ret(data = ip),
                                  get_sharpe_ratio(data = ip), get_max_drawdown(data = ip),
                                  get_upi(data = ip),
                                  get_cor_with_snp(data = ip),
                                  get_best_return(data = ip), get_worst_return(data = ip),
                                  get_hit_rate(data = ip), get_trades_per_year(data = ip))
                          names(op) <- c('Total return (pa)', 'Average return (pa)',
                                         'Sharpe ratio', 'Max drawdown',
                                         'Ulcer performance index',
                                         'Corr with SnP 500',
                                         'Best return (pa)', 'Worst return (pa)',
                                         'Hit rate', 'Trades per year')
                          return(op)
                        })
names(strat_results) <- strategy_names
strat_results <- do.call(rbind, strat_results)
xtable(strat_results)
