## These functions are designed assuming that all the input data sets
## have the following characteristics.
##
## > head(data)
##       returns   buy_date  sell_date
## 1  0.09413192 2010-12-28 2011-02-23
## 2  0.15437666 2011-03-23 2011-06-16
## 3 -0.10598286 2011-06-29 2011-07-28
## 4 -0.06924316 2011-10-11 2011-11-02
## 5  0.78984238 2011-11-30 2012-04-11
## 6 -0.15267176 2012-04-25 2012-05-15
## > 
## > str(data)
## 'data.frame':	23 obs. of  3 variables:
##  $ returns  : num  0.0941 0.1544 -0.106 -0.0692 0.7898 ...
##  $ buy_date : POSIXct, format: "2010-12-28" "2011-03-23" ...
##  $ sell_date: POSIXct, format: "2011-02-23" "2011-06-16" ...
## >

## This functions tells us the duration of each investment period
## during the period of backtesting. The 't' vector.
get_duration <- function(data)
  return(as.numeric(as.POSIXct(data$sell_date) - as.POSIXct(data$buy_date)))

## This functions converts the return vector to a per annum return
## vector. The per annum rate is calculated using simple interest as
## the asumption is we keep on re-investing a constant fixed amount
## each time the strategy indicates a buy position.
get_ret_pa_vector <- function(data)
  {
    ret <- data$returns; t = get_duration(data = data)
    ret_pa <- (ret * 365 / t)
    return(ret_pa)
  }

## This function gives the total return generated by the strategy (at
## a per annum rate) during the period of backtesting.The simulation's
## range/duration (sim_range) is assumed to be provided in days. This
## function also assumes that the environment in which this function
## is called contains the sim_range variable.
get_total_ret <- function(data)
  {
    r_strat <- sum(data$returns)
    return(r_strat * 365 / sim_range)
  }

## This function gives the average return generated by the strategy
## (at a per annum rate) over the various times we entered in a trade
## during the period of backtesting.
get_avg_ret <- function(data) return(mean(get_ret_pa_vector(data = data)))

## This function gives us the Sharpe Ratio of the returns generated by
## the strategies (at an annualised rate of return).
get_sharpe_ratio <- function(data)
  {
    ret <- get_ret_pa_vector(data = data)
    return(sum(ret)/sd(ret))
  }

## This function tells us the maximum return generated by the strategy
## in a trade amongst all trades indicated.
get_best_return <- function(data) return(max(get_ret_pa_vector(data = data)))

## This function tells us the minimum return generated by the strategy
## in a trade amongst all trades indicated.
get_worst_return <- function(data) return(min(get_ret_pa_vector(data = data)))

## This function tells us the hit rate of the strategy trades.
get_hit_rate <- function(data)
  {
    ret <- get_ret_pa_vector(data = data)
    return(length(which(ret > 0))/length(ret)*100)
  }

## This function tells us the average number of trades indicated by
## the strategy.
get_trades_per_year <- function(data) return(nrow(data)/sim_range*365)

## This function tells us the corelation of the strategy with S&P
## 500. This function also assumes that the environment in which this
## function is called contains the S&P 500 time series data-set under
## the name of data_snp.
get_cor_with_snp <- function(data)
  {
    snp_ret <- ((data_snp[which(as.POSIXct(names(data_snp)) %in% as.POSIXct(data$sell_date))]
                 -
                 data_snp[which(as.POSIXct(names(data_snp)) %in% as.POSIXct(data$buy_date))])/
                data_snp[which(as.POSIXct(names(data_snp)) %in% as.POSIXct(data$buy_date))])
    return(cor(snp_ret, data$returns))
  }

## This function calculates the maximum drawdown of a strategy. Draw
## down is the lowest trough (point) of the cumulative return
## generated by the strategy over the entire period of back
## testing. This is under the assumption that we re-invest the same
## anount each time we trade using the strategy signal.
get_max_drawdown <- function(data)
  {
    ret <- get_ret_pa_vector(data = data)
    ret_cum <- cumsum(ret)
    return(min(ret_cum))
  }

## This function gives us the Ulcer performance index of a strategy
## (at an annualised rate of return).
## For details refer to:
## http://www.quantshare.com/item-842-ulcer-performance-index
## http://volatilitymadesimple.com/the-ulcer-performance-index/
## https://en.wikipedia.org/wiki/Ulcer_index
get_upi <- function(data)
  {
    ret <- get_ret_pa_vector(data = data)
    ret_cum <- cumsum(ret)
    ui <- rep(0, (length(ret_cum) + 1))
    for(i in 2:length(ui))
      {
        ui[i] <- ret_cum[i] - max(ret_cum[1:(i - 1)])
      }
    ui <- sqrt(sum(ui*ui)/length(ui))
    return(sum(ret)/ui)
  }
